import { Metadata } from "next";
import { ReactNode } from "react";

import "./globals.css";
import AuthProvider from "@/context/oauth/AuthProivder";
import ScreensaverOverlay from "../components/shared/ScreensaverOverlay";
import FlyoutMenu from "@/components/shared/FlyoutMenu";
import CalendarProvider from "@/context/calendar/CalendarProvider";
import Header from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, header, flyout  }: { children: ReactNode, header: ReactNode, flyout: ReactNode }) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <AuthProvider>
          <CalendarProvider>
            <Header header={header} />
            <main>
              {children}
              <ScreensaverOverlay />
            </main>
            <FlyoutMenu menu={flyout} />
          </CalendarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
